version: '3.8'
services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - flasknet

  frontend:
    build: ./frontend
    container_name: node-frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - flasknet

networks:
  flasknet:
